# Generated by Django 5.2.4 on 2025-07-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.FloatField()),
            ],
        ),
    ]
