# Generated by Django 5.2.4 on 2025-07-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_products_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='file',
        ),
    ]
